//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 04:13:08 PM EDT 
//


package gov.nist.healthcare.unified.validation.message;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nist.healthcare.validation.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nist.healthcare.validation.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportHeader }
     * 
     */
    public ReportHeader createReportHeader() {
        return new ReportHeader();
    }

    /**
     * Create an instance of {@link ReportHeader.TestObjectReferenceList }
     * 
     */
    public ReportHeader.TestObjectReferenceList createReportHeaderTestObjectReferenceList() {
        return new ReportHeader.TestObjectReferenceList();
    }

    /**
     * Create an instance of {@link ReportHeader.ValidationObjectReferenceList }
     * 
     */
    public ReportHeader.ValidationObjectReferenceList createReportHeaderValidationObjectReferenceList() {
        return new ReportHeader.ValidationObjectReferenceList();
    }

    /**
     * Create an instance of {@link ReportHeader.TestObjectReferenceList.TestObjectReference }
     * 
     */
    public ReportHeader.TestObjectReferenceList.TestObjectReference createReportHeaderTestObjectReferenceListTestObjectReference() {
        return new ReportHeader.TestObjectReferenceList.TestObjectReference();
    }

    /**
     * Create an instance of {@link ReportHeader.ValidationObjectReferenceList.ValidationObjectReference }
     * 
     */
    public ReportHeader.ValidationObjectReferenceList.ValidationObjectReference createReportHeaderValidationObjectReferenceListValidationObjectReference() {
        return new ReportHeader.ValidationObjectReferenceList.ValidationObjectReference();
    }

}
