//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 04:13:08 PM EDT 
//


package gov.nist.healthcare.unified.validation.message;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StandardTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StandardTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HL7 V2"/>
 *     &lt;enumeration value="HL7 V3"/>
 *     &lt;enumeration value="CDA"/>
 *     &lt;enumeration value="DICOM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StandardTypeType")
@XmlEnum
public enum StandardTypeType {

    @XmlEnumValue("HL7 V2")
    HL_7_V_2("HL7 V2"),
    @XmlEnumValue("HL7 V3")
    HL_7_V_3("HL7 V3"),
    CDA("CDA"),
    DICOM("DICOM"),
    NCPDP("NCPDP");
    private final String value;

    StandardTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StandardTypeType fromValue(String v) {
        for (StandardTypeType c: StandardTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
