//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 04:13:08 PM EDT 
//


package gov.nist.healthcare.unified.validation.message.hl7.v2.report;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import gov.nist.healthcare.unified.validation.message.ReportHeader;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HeaderReport" type="{http://www.nist.gov/healthcare/validation/message}ReportHeader"/>
 *         &lt;element name="SpecificReport" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/report}HL7V2MessageReport"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerReport",
    "specificReport"
})
@XmlRootElement(name = "HL7V2MessageValidationReport")
public class HL7V2MessageValidationReport {

    @XmlElement(name = "HeaderReport", required = true)
    protected ReportHeader headerReport;
    @XmlElement(name = "SpecificReport", required = true)
    protected HL7V2MessageReport specificReport;

    /**
     * Gets the value of the headerReport property.
     * 
     * @return
     *     possible object is
     *     {@link ReportHeader }
     *     
     */
    public ReportHeader getHeaderReport() {
        return headerReport;
    }

    /**
     * Sets the value of the headerReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportHeader }
     *     
     */
    public void setHeaderReport(ReportHeader value) {
        this.headerReport = value;
    }

    /**
     * Gets the value of the specificReport property.
     * 
     * @return
     *     possible object is
     *     {@link HL7V2MessageReport }
     *     
     */
    public HL7V2MessageReport getSpecificReport() {
        return specificReport;
    }

    /**
     * Sets the value of the specificReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL7V2MessageReport }
     *     
     */
    public void setSpecificReport(HL7V2MessageReport value) {
        this.specificReport = value;
    }

}
