//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 04:13:08 PM EDT 
//

package gov.nist.healthcare.unified.validation.message.hl7.v2.report;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import gov.nist.healthcare.unified.message.EncodingConstants;
import gov.nist.healthcare.unified.profile.ProfileElement;
import gov.nist.healthcare.unified.validation.AssertionResultConstants;
import gov.nist.healthcare.unified.validation.AssertionTypeV2Constants;
import gov.nist.healthcare.unified.validation.ErrorSeverityConstants;
import gov.nist.healthcare.unified.validation.message.hl7.v2.context.HL7V2MessageValidationContextDefinition;

/**
 * <p>
 * Java class for HL7V2MessageReport complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="HL7V2MessageReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetaData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Profile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Organization" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="HL7Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Message">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="XmlMessage" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                             &lt;element name="Er7Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Filename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Encoding" use="required" type="{http://www.nist.gov/healthcare/message}EncodingConstants" />
 *                           &lt;attribute name="Transformed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Context" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}HL7V2MessageValidationContextDefinition" minOccurs="0"/>
 *                   &lt;element name="TestCase" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AssertionList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="Assertion">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Location">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                                       &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                                       &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="XPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="ProfileElement" type="{http://www.nist.gov/healthcare/profile}ProfileElement" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AssertionDeclaration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionTypeV2Constants" />
 *                           &lt;attribute name="Result" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionResultConstants" />
 *                           &lt;attribute name="Severity" use="required" type="{http://www.nist.gov/healthcare/validation}ErrorSeverityConstants" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HL7V2MessageReport", propOrder = { "metaData", "assertionList" })
public class HL7V2MessageReport {

	@XmlElement(name = "MetaData", required = true)
	protected HL7V2MessageReport.MetaData metaData;
	@XmlElement(name = "AssertionList")
	protected HL7V2MessageReport.AssertionList assertionList;

	/**
	 * Gets the value of the metaData property.
	 * 
	 * @return possible object is {@link HL7V2MessageReport.MetaData }
	 * 
	 */
	public HL7V2MessageReport.MetaData getMetaData() {
		return metaData;
	}

	/**
	 * Sets the value of the metaData property.
	 * 
	 * @param value
	 *            allowed object is {@link HL7V2MessageReport.MetaData }
	 * 
	 */
	public void setMetaData(HL7V2MessageReport.MetaData value) {
		this.metaData = value;
	}

	/**
	 * Gets the value of the assertionList property.
	 * 
	 * @return possible object is {@link HL7V2MessageReport.AssertionList }
	 * 
	 */
	public HL7V2MessageReport.AssertionList getAssertionList() {
		return assertionList;
	}

	/**
	 * Sets the value of the assertionList property.
	 * 
	 * @param value
	 *            allowed object is {@link HL7V2MessageReport.AssertionList }
	 * 
	 */
	public void setAssertionList(HL7V2MessageReport.AssertionList value) {
		this.assertionList = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence maxOccurs="unbounded">
	 *         &lt;element name="Assertion">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="Location">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
	 *                             &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
	 *                             &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                             &lt;element name="XPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                             &lt;element name="ProfileElement" type="{http://www.nist.gov/healthcare/profile}ProfileElement" minOccurs="0"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="AssertionDeclaration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionTypeV2Constants" />
	 *                 &lt;attribute name="Result" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionResultConstants" />
	 *                 &lt;attribute name="Severity" use="required" type="{http://www.nist.gov/healthcare/validation}ErrorSeverityConstants" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "assertion" })
	public static class AssertionList {

		@XmlElement(name = "Assertion", required = true)
		protected List<HL7V2MessageReport.AssertionList.Assertion> assertion;

		/**
		 * Gets the value of the assertion property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the assertion property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getAssertion().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link HL7V2MessageReport.AssertionList.Assertion }
		 * 
		 * 
		 */
		public List<HL7V2MessageReport.AssertionList.Assertion> getAssertion() {
			if (assertion == null) {
				assertion = new ArrayList<HL7V2MessageReport.AssertionList.Assertion>();
			}
			return this.assertion;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="Location">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
		 *                   &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
		 *                   &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                   &lt;element name="XPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                   &lt;element name="ProfileElement" type="{http://www.nist.gov/healthcare/profile}ProfileElement" minOccurs="0"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="AssertionDeclaration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="Type" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionTypeV2Constants" />
		 *       &lt;attribute name="Result" use="required" type="{http://www.nist.gov/healthcare/validation}AssertionResultConstants" />
		 *       &lt;attribute name="Severity" use="required" type="{http://www.nist.gov/healthcare/validation}ErrorSeverityConstants" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "location", "content", "description",
				"assertionDeclaration", "reference", "stackTrace", "metaData" })
		public static class Assertion {

			@XmlElement(name = "Location", required = true)
			protected HL7V2MessageReport.AssertionList.Assertion.Location location;
			@XmlElement(name = "Content")
			protected String content;
			@XmlElement(name = "Description", required = true)
			protected String description;
			@XmlElement(name = "AssertionDeclaration")
			protected String assertionDeclaration;
			@XmlElement(name = "Reference")
			protected String reference;
			@XmlAttribute(name = "Type", required = true)
			protected String type;
			@XmlAttribute(name = "Result", required = true)
			protected String result;
			@XmlAttribute(name = "Severity", required = true)
			protected ErrorSeverityConstants severity;
			@XmlElement(name = "StackTrace")
			protected StackTrace stackTrace;
			@XmlElement(name = "MetaData")
			protected gov.nist.healthcare.unified.validation.metadata.MetaData metaData;

			public gov.nist.healthcare.unified.validation.metadata.MetaData getMetaData() {
				return metaData;
			}

			public void setMetaData(
					gov.nist.healthcare.unified.validation.metadata.MetaData mdN) {
				this.metaData = mdN;
			}

			public StackTrace getStackTrace() {
				return stackTrace;
			}

			public void setStackTrace(StackTrace stackTrace) {
				this.stackTrace = stackTrace;
			}

			/**
			 * Gets the value of the location property.
			 * 
			 * @return possible object is
			 *         {@link HL7V2MessageReport.AssertionList.Assertion.Location }
			 * 
			 */
			public HL7V2MessageReport.AssertionList.Assertion.Location getLocation() {
				return location;
			}

			/**
			 * Sets the value of the location property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link HL7V2MessageReport.AssertionList.Assertion.Location }
			 * 
			 */
			public void setLocation(
					HL7V2MessageReport.AssertionList.Assertion.Location value) {
				this.location = value;
			}

			/**
			 * Gets the value of the content property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getContent() {
				return content;
			}

			/**
			 * Sets the value of the content property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setContent(String value) {
				this.content = value;
			}

			/**
			 * Gets the value of the description property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDescription() {
				return description;
			}

			/**
			 * Sets the value of the description property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDescription(String value) {
				this.description = value;
			}

			/**
			 * Gets the value of the assertionDeclaration property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getAssertionDeclaration() {
				return assertionDeclaration;
			}

			/**
			 * Sets the value of the assertionDeclaration property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setAssertionDeclaration(String value) {
				this.assertionDeclaration = value;
			}

			/**
			 * Gets the value of the reference property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getReference() {
				return reference;
			}

			/**
			 * Sets the value of the reference property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setReference(String value) {
				this.reference = value;
			}

			/**
			 * Gets the value of the type property.
			 * 
			 * @return possible object is {@link AssertionTypeV2Constants }
			 * 
			 */
			public String getType() {
				return type;
			}

			/**
			 * Sets the value of the type property.
			 * 
			 * @param value
			 *            allowed object is {@link AssertionTypeV2Constants }
			 * 
			 */
			public void setType(String value) {
				this.type = value;
			}

			/**
			 * Gets the value of the result property.
			 * 
			 * @return possible object is {@link AssertionResultConstants }
			 * 
			 */
			public String getResult() {
				return result;
			}

			/**
			 * Sets the value of the result property.
			 * 
			 * @param value
			 *            allowed object is {@link AssertionResultConstants }
			 * 
			 */
			public void setResult(String value) {
				this.result = value;
			}

			/**
			 * Gets the value of the severity property.
			 * 
			 * @return possible object is {@link ErrorSeverityConstants }
			 * 
			 */
			public ErrorSeverityConstants getSeverity() {
				return severity;
			}

			/**
			 * Sets the value of the severity property.
			 * 
			 * @param value
			 *            allowed object is {@link ErrorSeverityConstants }
			 * 
			 */
			public void setSeverity(ErrorSeverityConstants value) {
				this.severity = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
			 *         &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
			 *         &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *         &lt;element name="XPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *         &lt;element name="ProfileElement" type="{http://www.nist.gov/healthcare/profile}ProfileElement" minOccurs="0"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "line", "column", "path", "messageProfilePath", "messageProfilePositionPath", "messageInstancePathName", "messageInstancePositionPath",
					"xPath", "profileElement" })
			public static class Location {

				@XmlElement(name = "Line")
				protected Integer line;
				@XmlElement(name = "Column")
				protected Integer column;
				@XmlElement(name = "Path")
				protected String path;

				@XmlElement(name = "MessageProfilePath")
				protected String messageProfilePath;
				@XmlElement(name = "MessageProfilePositionPath")
				protected String messageProfilePositionPath;
				@XmlElement(name = "MessageInstancePathName")
				protected String messageInstancePathName;
				@XmlElement(name = "MessageInstancePositionPath")
				protected String messageInstancePositionPath;
				@XmlElement(name = "XPath")
				protected String xPath;
				@XmlElement(name = "ProfileElement")
				protected ProfileElement profileElement;

				/**
				 * Gets the value of the line property.
				 * 
				 * @return possible object is {@link Integer }
				 * 
				 */
				public Integer getLine() {
					return line;
				}

				/**
				 * Sets the value of the line property.
				 * 
				 * @param value
				 *            allowed object is {@link Integer }
				 * 
				 */
				public void setLine(Integer value) {
					this.line = value;
				}

				/**
				 * Gets the value of the column property.
				 * 
				 * @return possible object is {@link Integer }
				 * 
				 */
				public Integer getColumn() {
					return column;
				}

				/**
				 * Sets the value of the column property.
				 * 
				 * @param value
				 *            allowed object is {@link Integer }
				 * 
				 */
				public void setColumn(Integer value) {
					this.column = value;
				}

				/**
				 * Gets the value of the path property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getPath() {
					return path;
				}

				/**
				 * Sets the value of the path property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setPath(String value) {
					this.path = value;
				}

				/**
				 * Gets the value of the xPath property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getXPath() {
					return xPath;
				}

				/**
				 * Sets the value of the xPath property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setXPath(String value) {
					this.xPath = value;
				}

				/**
				 * Gets the value of the profileElement property.
				 * 
				 * @return possible object is {@link ProfileElement }
				 * 
				 */
				public ProfileElement getProfileElement() {
					return profileElement;
				}

				/**
				 * Sets the value of the profileElement property.
				 * 
				 * @param value
				 *            allowed object is {@link ProfileElement }
				 * 
				 */
				public void setProfileElement(ProfileElement value) {
					this.profileElement = value;
				}

				public String getMessageProfilePath() {
					return messageProfilePath;
				}

				public void setMessageProfilePath(String messageProfilePath) {
					this.messageProfilePath = messageProfilePath;
				}

				public String getMessageProfilePositionPath() {
					return messageProfilePositionPath;
				}

				public void setMessageProfilePositionPath(String messageProfilePositionPath) {
					this.messageProfilePositionPath = messageProfilePositionPath;
				}

				public String getMessageInstancePathName() {
					return messageInstancePathName;
				}

				public void setMessageInstancePathName(String messageInstancePathName) {
					this.messageInstancePathName = messageInstancePathName;
				}

				public String getMessageInstancePositionPath() {
					return messageInstancePositionPath;
				}

				public void setMessageInstancePositionPath(String messageInstancePositionPath) {
					this.messageInstancePositionPath = messageInstancePositionPath;
				}
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Profile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="Organization" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="HL7Version" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="Date" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Message">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="XmlMessage" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
	 *                   &lt;element name="Er7Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="Filename" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="Encoding" use="required" type="{http://www.nist.gov/healthcare/message}EncodingConstants" />
	 *                 &lt;attribute name="Transformed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Context" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}HL7V2MessageValidationContextDefinition" minOccurs="0"/>
	 *         &lt;element name="TestCase" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "profile", "message", "context",
			"testCase" })
	public static class MetaData {

		@XmlElement(name = "Profile", required = true)
		protected HL7V2MessageReport.MetaData.Profile profile;
		@XmlElement(name = "Message", required = true)
		protected HL7V2MessageReport.MetaData.Message message;
		@XmlElement(name = "Context")
		protected HL7V2MessageValidationContextDefinition context;
		@XmlElement(name = "TestCase")
		protected HL7V2MessageReport.MetaData.TestCase testCase;

		/**
		 * Gets the value of the profile property.
		 * 
		 * @return possible object is
		 *         {@link HL7V2MessageReport.MetaData.Profile }
		 * 
		 */
		public HL7V2MessageReport.MetaData.Profile getProfile() {
			return profile;
		}

		/**
		 * Sets the value of the profile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link HL7V2MessageReport.MetaData.Profile }
		 * 
		 */
		public void setProfile(HL7V2MessageReport.MetaData.Profile value) {
			this.profile = value;
		}

		/**
		 * Gets the value of the message property.
		 * 
		 * @return possible object is
		 *         {@link HL7V2MessageReport.MetaData.Message }
		 * 
		 */
		public HL7V2MessageReport.MetaData.Message getMessage() {
			return message;
		}

		/**
		 * Sets the value of the message property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link HL7V2MessageReport.MetaData.Message }
		 * 
		 */
		public void setMessage(HL7V2MessageReport.MetaData.Message value) {
			this.message = value;
		}

		/**
		 * Gets the value of the context property.
		 * 
		 * @return possible object is
		 *         {@link HL7V2MessageValidationContextDefinition }
		 * 
		 */
		public HL7V2MessageValidationContextDefinition getContext() {
			return context;
		}

		/**
		 * Sets the value of the context property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link HL7V2MessageValidationContextDefinition }
		 * 
		 */
		public void setContext(HL7V2MessageValidationContextDefinition value) {
			this.context = value;
		}

		/**
		 * Gets the value of the testCase property.
		 * 
		 * @return possible object is
		 *         {@link HL7V2MessageReport.MetaData.TestCase }
		 * 
		 */
		public HL7V2MessageReport.MetaData.TestCase getTestCase() {
			return testCase;
		}

		/**
		 * Sets the value of the testCase property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link HL7V2MessageReport.MetaData.TestCase }
		 * 
		 */
		public void setTestCase(HL7V2MessageReport.MetaData.TestCase value) {
			this.testCase = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="XmlMessage" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
		 *         &lt;element name="Er7Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="Filename" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="Encoding" use="required" type="{http://www.nist.gov/healthcare/message}EncodingConstants" />
		 *       &lt;attribute name="Transformed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "xmlMessage", "er7Message", "er7MessageHexFormatted" })
		public static class Message {

			@XmlElement(name = "XmlMessage")
			protected Object xmlMessage;
			@XmlElement(name = "Er7Message")
			protected String er7Message;
			@XmlElement(name = "Er7MessageHexFormatted")
			protected String er7MessageHexFormatted;
			@XmlAttribute(name = "Id")
			protected String id;
			@XmlAttribute(name = "Filename")
			protected String filename;
			@XmlAttribute(name = "Encoding", required = true)
			protected EncodingConstants encoding;
			@XmlAttribute(name = "Transformed", required = true)
			protected boolean transformed;

			/**
			 * Gets the value of the xmlMessage property.
			 * 
			 * @return possible object is {@link Object }
			 * 
			 */
			public Object getXmlMessage() {
				return xmlMessage;
			}

			/**
			 * Sets the value of the xmlMessage property.
			 * 
			 * @param value
			 *            allowed object is {@link Object }
			 * 
			 */
			public void setXmlMessage(Object value) {
				this.xmlMessage = value;
			}

			/**
			 * Gets the value of the er7Message property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getEr7Message() {
				return er7Message;
			}

			/**
			 * Sets the value of the er7Message property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setEr7Message(String value) {
				this.er7Message = value;
			}

			/**
			 * Gets the value of the id property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getId() {
				return id;
			}

			/**
			 * Sets the value of the id property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setId(String value) {
				this.id = value;
			}

			/**
			 * Gets the value of the filename property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFilename() {
				return filename;
			}

			/**
			 * Sets the value of the filename property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setFilename(String value) {
				this.filename = value;
			}

			/**
			 * Gets the value of the encoding property.
			 * 
			 * @return possible object is {@link EncodingConstants }
			 * 
			 */
			public EncodingConstants getEncoding() {
				return encoding;
			}

			/**
			 * Sets the value of the encoding property.
			 * 
			 * @param value
			 *            allowed object is {@link EncodingConstants }
			 * 
			 */
			public void setEncoding(EncodingConstants value) {
				this.encoding = value;
			}

			/**
			 * Gets the value of the transformed property.
			 * 
			 */
			public boolean isTransformed() {
				return transformed;
			}

			/**
			 * Sets the value of the transformed property.
			 * 
			 */
			public void setTransformed(boolean value) {
				this.transformed = value;
			}

			public String getEr7MessageHexFormatted() {
				return er7MessageHexFormatted;
			}

			public void setEr7MessageHexFormatted(String er7MessageHexFormatted) {
				this.er7MessageHexFormatted = er7MessageHexFormatted;
			}
			
			

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="Organization" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="HL7Version" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="Date" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Profile {

			@XmlAttribute(name = "Organization")
			protected String organization;
			@XmlAttribute(name = "Name")
			protected String name;
			@XmlAttribute(name = "Type")
			protected String type;
			@XmlAttribute(name = "Version")
			protected String version;
			@XmlAttribute(name = "HL7Version")
			protected String hl7Version;
			@XmlAttribute(name = "Date")
			protected String date;
			@XmlAttribute(name = "MessageType")
			protected String messageType;
			@XmlAttribute(name = "Identifier")
			protected String identifier;
			@XmlAttribute(name = "Specification")
			protected String specification;

			public String getHl7Version() {
				return hl7Version;
			}

			public String getSpecification() {
				return specification;
			}

			public void setSpecification(String specification) {
				this.specification = specification;
			}

			public void setHl7Version(String hl7Version) {
				this.hl7Version = hl7Version;
			}

			public String getIdentifier() {
				return identifier;
			}

			public void setIdentifier(String identifier) {
				this.identifier = identifier;
			}

			public String getMessageType() {
				return messageType;
			}

			public void setMessageType(String messageType) {
				this.messageType = messageType;
			}

			/**
			 * Gets the value of the organization property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getOrganization() {
				return organization;
			}

			/**
			 * Sets the value of the organization property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setOrganization(String value) {
				this.organization = value;
			}

			/**
			 * Gets the value of the name property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setName(String value) {
				this.name = value;
			}

			/**
			 * Gets the value of the type property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getType() {
				return type;
			}

			/**
			 * Sets the value of the type property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setType(String value) {
				this.type = value;
			}

			/**
			 * Gets the value of the version property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getVersion() {
				return version;
			}

			/**
			 * Sets the value of the version property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setVersion(String value) {
				this.version = value;
			}

			/**
			 * Gets the value of the hl7Version property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getHL7Version() {
				return hl7Version;
			}

			/**
			 * Sets the value of the hl7Version property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setHL7Version(String value) {
				this.hl7Version = value;
			}

			/**
			 * Gets the value of the date property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDate() {
				return date;
			}

			/**
			 * Sets the value of the date property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDate(String value) {
				this.date = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "description" })
		public static class TestCase {

			@XmlElement(name = "Description")
			protected String description;
			@XmlAttribute(name = "name", required = true)
			protected String name;

			/**
			 * Gets the value of the description property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDescription() {
				return description;
			}

			/**
			 * Sets the value of the description property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDescription(String value) {
				this.description = value;
			}

			/**
			 * Gets the value of the name property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setName(String value) {
				this.name = value;
			}

		}

	}

}
