//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 04:13:08 PM EDT 
//


package gov.nist.healthcare.unified.validation.message.hl7.v2.report;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nist.healthcare.validation.message.hl7.v2.report package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nist.healthcare.validation.message.hl7.v2.report
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HL7V2MessageReport }
     * 
     */
    public HL7V2MessageReport createHL7V2MessageReport() {
        return new HL7V2MessageReport();
    }

    /**
     * Create an instance of {@link HL7V2MessageReport.AssertionList }
     * 
     */
    public HL7V2MessageReport.AssertionList createHL7V2MessageReportAssertionList() {
        return new HL7V2MessageReport.AssertionList();
    }

    /**
     * Create an instance of {@link HL7V2MessageReport.AssertionList.Assertion }
     * 
     */
    public HL7V2MessageReport.AssertionList.Assertion createHL7V2MessageReportAssertionListAssertion() {
        return new HL7V2MessageReport.AssertionList.Assertion();
    }

    /**
     * Create an instance of {@link HL7V2MessageReport.MetaData }
     * 
     */
    public HL7V2MessageReport.MetaData createHL7V2MessageReportMetaData() {
        return new HL7V2MessageReport.MetaData();
    }

    /**
     * Create an instance of {@link HL7V2MessageValidationReport }
     * 
     */
    public HL7V2MessageValidationReport createHL7V2MessageValidationReport() {
        return new HL7V2MessageValidationReport();
    }

    /**
     * Create an instance of {@link HL7V2MessageReport.AssertionList.Assertion.Location }
     * 
     */
    public HL7V2MessageReport.AssertionList.Assertion.Location createHL7V2MessageReportAssertionListAssertionLocation() {
        return new HL7V2MessageReport.AssertionList.Assertion.Location();
    }

    /**
     * Create an instance of {@link HL7V2MessageReport.MetaData.Profile }
     * 
     */
    public HL7V2MessageReport.MetaData.Profile createHL7V2MessageReportMetaDataProfile() {
        return new HL7V2MessageReport.MetaData.Profile();
    }

    /**
     * Create an instance of {@link HL7V2MessageReport.MetaData.Message }
     * 
     */
    public HL7V2MessageReport.MetaData.Message createHL7V2MessageReportMetaDataMessage() {
        return new HL7V2MessageReport.MetaData.Message();
    }

    /**
     * Create an instance of {@link HL7V2MessageReport.MetaData.TestCase }
     * 
     */
    public HL7V2MessageReport.MetaData.TestCase createHL7V2MessageReportMetaDataTestCase() {
        return new HL7V2MessageReport.MetaData.TestCase();
    }

}
