//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 04:13:08 PM EDT 
//


package gov.nist.healthcare.unified.validation.message.hl7.v2.context;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatatypeCheckConstants.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DatatypeCheckConstants">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HD"/>
 *     &lt;enumeration value="CE"/>
 *     &lt;enumeration value="CWE"/>
 *     &lt;enumeration value="CNE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DatatypeCheckConstants")
@XmlEnum
public enum DatatypeCheckConstants {

    HD,
    CE,
    CWE,
    CNE;

    public String value() {
        return name();
    }

    public static DatatypeCheckConstants fromValue(String v) {
        return valueOf(v);
    }

}
