//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 04:13:08 PM EDT 
//


package gov.nist.healthcare.unified.validation.message.hl7.v2.context;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import gov.nist.healthcare.unified.message.MessageElement;
import gov.nist.healthcare.unified.validation.AssertionResultConstants;
import gov.nist.healthcare.unified.validation.PluginCheckType;


/**
 * <p>Java class for HL7V2MessageValidationContextDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HL7V2MessageValidationContextDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValidationConfiguration">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HL7Tables">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice minOccurs="0">
 *                             &lt;element name="HL7Table" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="All">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;length value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="None">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;length value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="UserTables">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice minOccurs="0">
 *                             &lt;element name="UserTable" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="All">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;length value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="None">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;length value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TablesToExclude" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Table" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FailureInterpretation" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}MessageFailureInterpretationV2"/>
 *         &lt;element name="MessageInstanceSpecificValues" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}MessageInstanceSpecificValuesV2" minOccurs="0"/>
 *         &lt;element name="IfThenElse" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="If" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}DataValueLocationItemV2"/>
 *                   &lt;element name="Then" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}DataValueLocationItemV2"/>
 *                   &lt;element name="Else" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}DataValueLocationItemV2" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="MatchingSegmentInstanceNumber" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="MatchingFieldInstanceNumber" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DatatypeCheck" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Location" type="{http://www.nist.gov/healthcare/message}MessageElement"/>
 *                   &lt;element name="Comment" type="{http://www.nist.gov/healthcare/validation}CommentType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Datatype" use="required" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}DatatypeCheckConstants" />
 *                 &lt;attribute name="AssertionResult" type="{http://www.nist.gov/healthcare/validation}AssertionResultConstants" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PluginCheck" type="{http://www.nist.gov/healthcare/validation}PluginCheckType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HL7V2MessageValidationContextDefinition", propOrder = {
    "validationConfiguration",
    "failureInterpretation",
    "messageInstanceSpecificValues",
    "ifThenElse",
    "datatypeCheck",
    "pluginCheck"
})
public class HL7V2MessageValidationContextDefinition {

    @XmlElement(name = "ValidationConfiguration", required = true)
    protected HL7V2MessageValidationContextDefinition.ValidationConfiguration validationConfiguration;
    @XmlElement(name = "FailureInterpretation", required = true)
    protected MessageFailureInterpretationV2 failureInterpretation;
    @XmlElement(name = "MessageInstanceSpecificValues")
    protected MessageInstanceSpecificValuesV2 messageInstanceSpecificValues;
    @XmlElement(name = "IfThenElse")
    protected List<HL7V2MessageValidationContextDefinition.IfThenElse> ifThenElse;
    @XmlElement(name = "DatatypeCheck")
    protected List<HL7V2MessageValidationContextDefinition.DatatypeCheck> datatypeCheck;
    @XmlElement(name = "PluginCheck")
    protected List<PluginCheckType> pluginCheck;

    /**
     * Gets the value of the validationConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration }
     *     
     */
    public HL7V2MessageValidationContextDefinition.ValidationConfiguration getValidationConfiguration() {
        return validationConfiguration;
    }

    /**
     * Sets the value of the validationConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration }
     *     
     */
    public void setValidationConfiguration(HL7V2MessageValidationContextDefinition.ValidationConfiguration value) {
        this.validationConfiguration = value;
    }

    /**
     * Gets the value of the failureInterpretation property.
     * 
     * @return
     *     possible object is
     *     {@link MessageFailureInterpretationV2 }
     *     
     */
    public MessageFailureInterpretationV2 getFailureInterpretation() {
        return failureInterpretation;
    }

    /**
     * Sets the value of the failureInterpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageFailureInterpretationV2 }
     *     
     */
    public void setFailureInterpretation(MessageFailureInterpretationV2 value) {
        this.failureInterpretation = value;
    }

    /**
     * Gets the value of the messageInstanceSpecificValues property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInstanceSpecificValuesV2 }
     *     
     */
    public MessageInstanceSpecificValuesV2 getMessageInstanceSpecificValues() {
        return messageInstanceSpecificValues;
    }

    /**
     * Sets the value of the messageInstanceSpecificValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInstanceSpecificValuesV2 }
     *     
     */
    public void setMessageInstanceSpecificValues(MessageInstanceSpecificValuesV2 value) {
        this.messageInstanceSpecificValues = value;
    }

    /**
     * Gets the value of the ifThenElse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ifThenElse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIfThenElse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HL7V2MessageValidationContextDefinition.IfThenElse }
     * 
     * 
     */
    public List<HL7V2MessageValidationContextDefinition.IfThenElse> getIfThenElse() {
        if (ifThenElse == null) {
            ifThenElse = new ArrayList<HL7V2MessageValidationContextDefinition.IfThenElse>();
        }
        return this.ifThenElse;
    }

    /**
     * Gets the value of the datatypeCheck property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datatypeCheck property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatatypeCheck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HL7V2MessageValidationContextDefinition.DatatypeCheck }
     * 
     * 
     */
    public List<HL7V2MessageValidationContextDefinition.DatatypeCheck> getDatatypeCheck() {
        if (datatypeCheck == null) {
            datatypeCheck = new ArrayList<HL7V2MessageValidationContextDefinition.DatatypeCheck>();
        }
        return this.datatypeCheck;
    }

    /**
     * Gets the value of the pluginCheck property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pluginCheck property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPluginCheck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PluginCheckType }
     * 
     * 
     */
    public List<PluginCheckType> getPluginCheck() {
        if (pluginCheck == null) {
            pluginCheck = new ArrayList<PluginCheckType>();
        }
        return this.pluginCheck;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Location" type="{http://www.nist.gov/healthcare/message}MessageElement"/>
     *         &lt;element name="Comment" type="{http://www.nist.gov/healthcare/validation}CommentType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Datatype" use="required" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}DatatypeCheckConstants" />
     *       &lt;attribute name="AssertionResult" type="{http://www.nist.gov/healthcare/validation}AssertionResultConstants" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "location",
        "comment"
    })
    public static class DatatypeCheck {

        @XmlElement(name = "Location", required = true)
        protected MessageElement location;
        @XmlElement(name = "Comment")
        protected String comment;
        @XmlAttribute(name = "Datatype", required = true)
        protected DatatypeCheckConstants datatype;
        @XmlAttribute(name = "AssertionResult")
        protected AssertionResultConstants assertionResult;

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link MessageElement }
         *     
         */
        public MessageElement getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link MessageElement }
         *     
         */
        public void setLocation(MessageElement value) {
            this.location = value;
        }

        /**
         * Gets the value of the comment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComment() {
            return comment;
        }

        /**
         * Sets the value of the comment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComment(String value) {
            this.comment = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link DatatypeCheckConstants }
         *     
         */
        public DatatypeCheckConstants getDatatype() {
            return datatype;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatatypeCheckConstants }
         *     
         */
        public void setDatatype(DatatypeCheckConstants value) {
            this.datatype = value;
        }

        /**
         * Gets the value of the assertionResult property.
         * 
         * @return
         *     possible object is
         *     {@link AssertionResultConstants }
         *     
         */
        public AssertionResultConstants getAssertionResult() {
            return assertionResult;
        }

        /**
         * Sets the value of the assertionResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link AssertionResultConstants }
         *     
         */
        public void setAssertionResult(AssertionResultConstants value) {
            this.assertionResult = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="If" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}DataValueLocationItemV2"/>
     *         &lt;element name="Then" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}DataValueLocationItemV2"/>
     *         &lt;element name="Else" type="{http://www.nist.gov/healthcare/validation/message/hl7/v2/context}DataValueLocationItemV2" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="MatchingSegmentInstanceNumber" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="MatchingFieldInstanceNumber" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_if",
        "then",
        "_else"
    })
    public static class IfThenElse {

        @XmlElement(name = "If", required = true)
        protected DataValueLocationItemV2 _if;
        @XmlElement(name = "Then", required = true)
        protected DataValueLocationItemV2 then;
        @XmlElement(name = "Else")
        protected DataValueLocationItemV2 _else;
        @XmlAttribute(name = "MatchingSegmentInstanceNumber")
        protected Boolean matchingSegmentInstanceNumber;
        @XmlAttribute(name = "MatchingFieldInstanceNumber")
        protected Boolean matchingFieldInstanceNumber;

        /**
         * Gets the value of the if property.
         * 
         * @return
         *     possible object is
         *     {@link DataValueLocationItemV2 }
         *     
         */
        public DataValueLocationItemV2 getIf() {
            return _if;
        }

        /**
         * Sets the value of the if property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataValueLocationItemV2 }
         *     
         */
        public void setIf(DataValueLocationItemV2 value) {
            this._if = value;
        }

        /**
         * Gets the value of the then property.
         * 
         * @return
         *     possible object is
         *     {@link DataValueLocationItemV2 }
         *     
         */
        public DataValueLocationItemV2 getThen() {
            return then;
        }

        /**
         * Sets the value of the then property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataValueLocationItemV2 }
         *     
         */
        public void setThen(DataValueLocationItemV2 value) {
            this.then = value;
        }

        /**
         * Gets the value of the else property.
         * 
         * @return
         *     possible object is
         *     {@link DataValueLocationItemV2 }
         *     
         */
        public DataValueLocationItemV2 getElse() {
            return _else;
        }

        /**
         * Sets the value of the else property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataValueLocationItemV2 }
         *     
         */
        public void setElse(DataValueLocationItemV2 value) {
            this._else = value;
        }

        /**
         * Gets the value of the matchingSegmentInstanceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMatchingSegmentInstanceNumber() {
            return matchingSegmentInstanceNumber;
        }

        /**
         * Sets the value of the matchingSegmentInstanceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMatchingSegmentInstanceNumber(Boolean value) {
            this.matchingSegmentInstanceNumber = value;
        }

        /**
         * Gets the value of the matchingFieldInstanceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMatchingFieldInstanceNumber() {
            return matchingFieldInstanceNumber;
        }

        /**
         * Sets the value of the matchingFieldInstanceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMatchingFieldInstanceNumber(Boolean value) {
            this.matchingFieldInstanceNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HL7Tables">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice minOccurs="0">
     *                   &lt;element name="HL7Table" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="All">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;length value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="None">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;length value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="UserTables">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice minOccurs="0">
     *                   &lt;element name="UserTable" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="All">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;length value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="None">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;length value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TablesToExclude" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Table" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hl7Tables",
        "userTables",
        "tablesToExclude"
    })
    public static class ValidationConfiguration {

        @XmlElement(name = "HL7Tables", required = true)
        protected HL7V2MessageValidationContextDefinition.ValidationConfiguration.HL7Tables hl7Tables;
        @XmlElement(name = "UserTables", required = true)
        protected HL7V2MessageValidationContextDefinition.ValidationConfiguration.UserTables userTables;
        @XmlElement(name = "TablesToExclude")
        protected HL7V2MessageValidationContextDefinition.ValidationConfiguration.TablesToExclude tablesToExclude;

        /**
         * Gets the value of the hl7Tables property.
         * 
         * @return
         *     possible object is
         *     {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration.HL7Tables }
         *     
         */
        public HL7V2MessageValidationContextDefinition.ValidationConfiguration.HL7Tables getHL7Tables() {
            return hl7Tables;
        }

        /**
         * Sets the value of the hl7Tables property.
         * 
         * @param value
         *     allowed object is
         *     {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration.HL7Tables }
         *     
         */
        public void setHL7Tables(HL7V2MessageValidationContextDefinition.ValidationConfiguration.HL7Tables value) {
            this.hl7Tables = value;
        }

        /**
         * Gets the value of the userTables property.
         * 
         * @return
         *     possible object is
         *     {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration.UserTables }
         *     
         */
        public HL7V2MessageValidationContextDefinition.ValidationConfiguration.UserTables getUserTables() {
            return userTables;
        }

        /**
         * Sets the value of the userTables property.
         * 
         * @param value
         *     allowed object is
         *     {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration.UserTables }
         *     
         */
        public void setUserTables(HL7V2MessageValidationContextDefinition.ValidationConfiguration.UserTables value) {
            this.userTables = value;
        }

        /**
         * Gets the value of the tablesToExclude property.
         * 
         * @return
         *     possible object is
         *     {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration.TablesToExclude }
         *     
         */
        public HL7V2MessageValidationContextDefinition.ValidationConfiguration.TablesToExclude getTablesToExclude() {
            return tablesToExclude;
        }

        /**
         * Sets the value of the tablesToExclude property.
         * 
         * @param value
         *     allowed object is
         *     {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration.TablesToExclude }
         *     
         */
        public void setTablesToExclude(HL7V2MessageValidationContextDefinition.ValidationConfiguration.TablesToExclude value) {
            this.tablesToExclude = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice minOccurs="0">
         *         &lt;element name="HL7Table" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="All">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="None">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hl7Table",
            "all",
            "none"
        })
        public static class HL7Tables {

            @XmlElement(name = "HL7Table")
            protected List<String> hl7Table;
            @XmlElement(name = "All")
            protected String all;
            @XmlElement(name = "None")
            protected String none;

            /**
             * Gets the value of the hl7Table property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the hl7Table property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHL7Table().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getHL7Table() {
                if (hl7Table == null) {
                    hl7Table = new ArrayList<String>();
                }
                return this.hl7Table;
            }

            /**
             * Gets the value of the all property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAll() {
                return all;
            }

            /**
             * Sets the value of the all property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAll(String value) {
                this.all = value;
            }

            /**
             * Gets the value of the none property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNone() {
                return none;
            }

            /**
             * Sets the value of the none property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNone(String value) {
                this.none = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Table" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "table"
        })
        public static class TablesToExclude {

            @XmlElement(name = "Table")
            protected List<String> table;

            /**
             * Gets the value of the table property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the table property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTable().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getTable() {
                if (table == null) {
                    table = new ArrayList<String>();
                }
                return this.table;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice minOccurs="0">
         *         &lt;element name="UserTable" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="All">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="None">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "userTable",
            "all",
            "none"
        })
        public static class UserTables {

            @XmlElement(name = "UserTable")
            protected List<String> userTable;
            @XmlElement(name = "All")
            protected String all;
            @XmlElement(name = "None")
            protected String none;

            /**
             * Gets the value of the userTable property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the userTable property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getUserTable().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getUserTable() {
                if (userTable == null) {
                    userTable = new ArrayList<String>();
                }
                return this.userTable;
            }

            /**
             * Gets the value of the all property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAll() {
                return all;
            }

            /**
             * Sets the value of the all property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAll(String value) {
                this.all = value;
            }

            /**
             * Gets the value of the none property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNone() {
                return none;
            }

            /**
             * Sets the value of the none property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNone(String value) {
                this.none = value;
            }

        }

    }

}
