//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 04:13:08 PM EDT 
//


package gov.nist.healthcare.unified.validation.message.hl7.v2.context;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nist.healthcare.validation.message.hl7.v2.context package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HL7V2MessageValidationContextDefinition_QNAME = new QName("http://www.nist.gov/healthcare/validation/message/hl7/v2/context", "HL7V2MessageValidationContextDefinition");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nist.healthcare.validation.message.hl7.v2.context
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataValueLocationItemV2 }
     * 
     */
    public DataValueLocationItemV2 createDataValueLocationItemV2() {
        return new DataValueLocationItemV2();
    }

    /**
     * Create an instance of {@link HL7V2MessageValidationContextDefinition }
     * 
     */
    public HL7V2MessageValidationContextDefinition createHL7V2MessageValidationContextDefinition() {
        return new HL7V2MessageValidationContextDefinition();
    }

    /**
     * Create an instance of {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration }
     * 
     */
    public HL7V2MessageValidationContextDefinition.ValidationConfiguration createHL7V2MessageValidationContextDefinitionValidationConfiguration() {
        return new HL7V2MessageValidationContextDefinition.ValidationConfiguration();
    }

    /**
     * Create an instance of {@link MessageFailureV2 }
     * 
     */
    public MessageFailureV2 createMessageFailureV2() {
        return new MessageFailureV2();
    }

    /**
     * Create an instance of {@link MessageInstanceSpecificValuesV2 }
     * 
     */
    public MessageInstanceSpecificValuesV2 createMessageInstanceSpecificValuesV2() {
        return new MessageInstanceSpecificValuesV2();
    }

    /**
     * Create an instance of {@link MessageFailureInterpretationV2 }
     * 
     */
    public MessageFailureInterpretationV2 createMessageFailureInterpretationV2() {
        return new MessageFailureInterpretationV2();
    }

    /**
     * Create an instance of {@link DataValueLocationItemV2 .Location }
     * 
     */
    public DataValueLocationItemV2 .Location createDataValueLocationItemV2Location() {
        return new DataValueLocationItemV2 .Location();
    }

    /**
     * Create an instance of {@link HL7V2MessageValidationContextDefinition.IfThenElse }
     * 
     */
    public HL7V2MessageValidationContextDefinition.IfThenElse createHL7V2MessageValidationContextDefinitionIfThenElse() {
        return new HL7V2MessageValidationContextDefinition.IfThenElse();
    }

    /**
     * Create an instance of {@link HL7V2MessageValidationContextDefinition.DatatypeCheck }
     * 
     */
    public HL7V2MessageValidationContextDefinition.DatatypeCheck createHL7V2MessageValidationContextDefinitionDatatypeCheck() {
        return new HL7V2MessageValidationContextDefinition.DatatypeCheck();
    }

    /**
     * Create an instance of {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration.HL7Tables }
     * 
     */
    public HL7V2MessageValidationContextDefinition.ValidationConfiguration.HL7Tables createHL7V2MessageValidationContextDefinitionValidationConfigurationHL7Tables() {
        return new HL7V2MessageValidationContextDefinition.ValidationConfiguration.HL7Tables();
    }

    /**
     * Create an instance of {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration.UserTables }
     * 
     */
    public HL7V2MessageValidationContextDefinition.ValidationConfiguration.UserTables createHL7V2MessageValidationContextDefinitionValidationConfigurationUserTables() {
        return new HL7V2MessageValidationContextDefinition.ValidationConfiguration.UserTables();
    }

    /**
     * Create an instance of {@link HL7V2MessageValidationContextDefinition.ValidationConfiguration.TablesToExclude }
     * 
     */
    public HL7V2MessageValidationContextDefinition.ValidationConfiguration.TablesToExclude createHL7V2MessageValidationContextDefinitionValidationConfigurationTablesToExclude() {
        return new HL7V2MessageValidationContextDefinition.ValidationConfiguration.TablesToExclude();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HL7V2MessageValidationContextDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v2/context", name = "HL7V2MessageValidationContextDefinition")
    public JAXBElement<HL7V2MessageValidationContextDefinition> createHL7V2MessageValidationContextDefinition(HL7V2MessageValidationContextDefinition value) {
        return new JAXBElement<HL7V2MessageValidationContextDefinition>(_HL7V2MessageValidationContextDefinition_QNAME, HL7V2MessageValidationContextDefinition.class, null, value);
    }

}
