//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 04:13:08 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nist.gov/healthcare/validation/message/hl7/v2/context", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nist.healthcare.unified.validation.message.hl7.v2.context;
